---
- hosts: app
  gather_facts: no
  become: yes
  
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

- hosts: app
  gather_facts: no
  vars:
    image: geocoder
  
  tasks:
    - name: setup facts
      set_fact:
        timestamp: "{{lookup('pipe', 'date -u +%Y%m%d%H%M%S')}}"
    - name: build docker image
      delegate_to: localhost
      docker_image:
        build:
          path: ../
          pull: no
        name: '{{image}}'
        source: build
        force_source: yes
    - name: save image to file
      delegate_to: localhost
      docker_image:
        name: '{{image}}'
        tag: latest
        archive_path: '{{image}}.tar'
        source: local
    - name: compress image
      delegate_to: localhost
      archive:
        path: '{{image}}.tar'
        dest: '{{image}}.tar.gz'
        remove: yes
    - name: upload image
      copy:
        src: '{{image}}.tar.gz'
        dest: '/tmp/{{timestamp}}-{{image}}.tar.gz'
    - name: extract image
      shell: 'gunzip /tmp/{{timestamp}}-{{image}}.tar.gz'
    - name: load image
      become: yes
      docker_image:
        name: '{{image}}'
        load_path: '/tmp/{{timestamp}}-{{image}}.tar'
        source: load
        force_source: yes
    - name: remove image file
      file: 
        path: '/tmp/{{timestamp}}-{{image}}.tar'
        state: absent
    - name: start geocoder container
      become: yes
      docker_container:
          name: '{{image}}'
          image: '{{image}}'
          network_mode: host
          restart_policy: on-failure
          restart_retries: 10
          tty: yes
          state: started
          env_file: '/home/{{ansible_user}}/.env'
